/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospitalmanagementsystem;

import javax.swing.JOptionPane;

/**
 *
 * @author SABINA
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Heading = new javax.swing.JPanel();
        Head = new javax.swing.JLabel();
        LoginF = new javax.swing.JPanel();
        Username = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        UsernameF = new javax.swing.JTextField();
        PasswordF = new javax.swing.JPasswordField();
        loginF = new javax.swing.JButton();
        CloseF = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Heading.setBackground(new java.awt.Color(204, 204, 204));

        Head.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Head.setText("Hospital Management System");

        javax.swing.GroupLayout HeadingLayout = new javax.swing.GroupLayout(Heading);
        Heading.setLayout(HeadingLayout);
        HeadingLayout.setHorizontalGroup(
            HeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeadingLayout.createSequentialGroup()
                .addGap(536, 536, 536)
                .addComponent(Head)
                .addContainerGap(643, Short.MAX_VALUE))
        );
        HeadingLayout.setVerticalGroup(
            HeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeadingLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(Head)
                .addGap(35, 35, 35))
        );

        getContentPane().add(Heading, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1520, 100));

        LoginF.setBackground(new java.awt.Color(204, 204, 204));

        Username.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Username.setText("Username");

        Password.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Password.setText("Password");

        UsernameF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UsernameF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameFActionPerformed(evt);
            }
        });

        PasswordF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PasswordF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFActionPerformed(evt);
            }
        });

        loginF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        loginF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagementsystem/login (3).png"))); // NOI18N
        loginF.setText("Login");
        loginF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginFActionPerformed(evt);
            }
        });

        CloseF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CloseF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagementsystem/close.png"))); // NOI18N
        CloseF.setText("Close");
        CloseF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseFActionPerformed(evt);
            }
        });

        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jCheckBox1.setText("Showpassword");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LoginFLayout = new javax.swing.GroupLayout(LoginF);
        LoginF.setLayout(LoginFLayout);
        LoginFLayout.setHorizontalGroup(
            LoginFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginFLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(loginF)
                .addGap(41, 41, 41)
                .addComponent(CloseF)
                .addGap(0, 69, Short.MAX_VALUE))
            .addGroup(LoginFLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(LoginFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Username)
                    .addComponent(Password))
                .addGap(38, 38, 38)
                .addGroup(LoginFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginFLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jCheckBox1))
                    .addComponent(UsernameF, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordF, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LoginFLayout.setVerticalGroup(
            LoginFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginFLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(LoginFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsernameF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Username))
                .addGap(26, 26, 26)
                .addGroup(LoginFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Password)
                    .addComponent(PasswordF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(LoginFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginF)
                    .addComponent(CloseF))
                .addContainerGap())
        );

        getContentPane().add(LoginF, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, 410, 230));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagementsystem/background.jpg"))); // NOI18N
        Background.setMaximumSize(new java.awt.Dimension(1920, 1080));
        Background.setMinimumSize(new java.awt.Dimension(1920, 1080));
        Background.setPreferredSize(new java.awt.Dimension(1920, 1080));
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsernameFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameFActionPerformed

    private void PasswordFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFActionPerformed

    private void loginFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginFActionPerformed
        // TODO add your handling code here:
        if(UsernameF.getText ().equals("hospital")&&PasswordF.getText().equals("admin"))
        {
            setVisible(false);
            new Home().setVisible(true);
        }
        else
            JOptionPane.showMessageDialog(null,"<html> <b style=\"color:red; font-size: 10px\">Incorrect Username and password </html>");
    }//GEN-LAST:event_loginFActionPerformed

    private void CloseFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseFActionPerformed
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(null,"Do you want to close this appliction ","Select" ,JOptionPane.YES_NO_OPTION);
        if(a==0)
            System.exit(0);
    }//GEN-LAST:event_CloseFActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if(jCheckBox1.isSelected())
        {
            PasswordF.setEchoChar((char)0);
             }
            else
            PasswordF.setEchoChar('*');
       
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton CloseF;
    private javax.swing.JLabel Head;
    private javax.swing.JPanel Heading;
    private javax.swing.JPanel LoginF;
    private javax.swing.JLabel Password;
    private javax.swing.JPasswordField PasswordF;
    private javax.swing.JLabel Username;
    private javax.swing.JTextField UsernameF;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JButton loginF;
    // End of variables declaration//GEN-END:variables
}
