
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospitalmanagementsystem;

/*
 *
 * @author SABINA
 */
import project.DBConnection;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class updateDeletePatientRecord extends javax.swing.JFrame {
    String PatientID;
//public void close()
//{
//    patientIdF.setVisible(true);
//    NameF.setText("");
//    ContactNoF.setText("");
//    AgeF.setText("");
//    GenderF.setText("");
//    BloodGroupF.setText("");
//    AddressF.setText("");
//    jTextField8.setText("");
////    jComboBox1.removeAllItems();
//}
        
    /**
     * Creates new form updatePatientRecord
     */
    public updateDeletePatientRecord() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        patientIdF = new javax.swing.JTextField();
        NameF = new javax.swing.JTextField();
        ContactNoF = new javax.swing.JTextField();
        AgeF = new javax.swing.JTextField();
        BloodGroupF = new javax.swing.JTextField();
        AddressF = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(480, 150));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("PatientID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 54, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 107, 61, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("ContactNo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 143, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Age");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 187, 58, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Gender");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 231, 58, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Blood Group");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 275, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Address");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 319, 86, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Any Major Diseases Suffered Earlier");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 360, 338, -1));

        patientIdF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        patientIdF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientIdFActionPerformed(evt);
            }
        });
        getContentPane().add(patientIdF, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 54, 202, -1));

        NameF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(NameF, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 101, 202, -1));

        ContactNoF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ContactNoF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactNoFActionPerformed(evt);
            }
        });
        getContentPane().add(ContactNoF, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 140, 202, -1));

        AgeF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AgeF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgeFActionPerformed(evt);
            }
        });
        getContentPane().add(AgeF, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 184, 202, -1));

        BloodGroupF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BloodGroupF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BloodGroupFActionPerformed(evt);
            }
        });
        getContentPane().add(BloodGroupF, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 272, 202, -1));

        AddressF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AddressF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressFActionPerformed(evt);
            }
        });
        getContentPane().add(AddressF, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 316, 202, -1));

        jTextField8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 398, 408, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagementsystem/search.png"))); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 54, 125, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagementsystem/update2.png"))); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, -1, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagementsystem/close.png"))); // NOI18N
        jButton3.setText("Close");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 448, -1, -1));

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagementsystem/delete.png"))); // NOI18N
        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 450, -1, 40));

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 232, 200, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void patientIdFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientIdFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientIdFActionPerformed

    private void ContactNoFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactNoFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContactNoFActionPerformed

    private void AgeFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgeFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgeFActionPerformed

    private void BloodGroupFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BloodGroupFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BloodGroupFActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void AddressFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressFActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
//        close();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        PatientID=patientIdF.getText();
        try{
           Connection cons = DBConnection.getcon();
           Statement st =cons.createStatement();
           ResultSet rs =st.executeQuery("select *from patient where PatientID='"+PatientID+"'");
           if(rs.next())
           {
               NameF.setText(rs.getString(2));
               ContactNoF.setText(rs.getString(3));
               AgeF.setText(rs.getString(4));
               jComboBox1.setSelectedItem(rs.getString(5));
               BloodGroupF.setText(rs.getString(6));
               AddressF.setText(rs.getString(7));
               jTextField8.setText(rs.getString(8));
               patientIdF.setEditable(false);
               
           }
           else
               JOptionPane.showMessageDialog(null, "PatientID does not Exist");
//           close();
        }
        catch(Exception e)
        {
        JOptionPane.showMessageDialog(null, e);
        }
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String PatientID=patientIdF.getText();
        String Name=NameF.getText();
        String Contact=ContactNoF.getText();
        String Age=AgeF.getText();
//        String Gender=(String)jComboBox2.getSelectedItem();
        String Gender=(String)jComboBox1.getSelectedItem();
        String BloodGroup=BloodGroupF.getText();
        String Address=AddressF.getText();
        String AnymajorDiseases=jTextField8.getText();
        try{
          Connection cons=DBConnection.getcon();
          Statement st=cons.createStatement();
          st.executeUpdate("UPDATE patient set PatientId='"+this.PatientID+"', Name='"+Name+"',ContactNo='"+Contact+"',Age='"+Age+"',Gender='"+Gender+"',BloodGroup='"+BloodGroup+"',Address='"+Address+"',MajorDisease='"+AnymajorDiseases+"'where patientID='"+this.PatientID+"'");
          JOptionPane.showMessageDialog(null, "Successfully Update");
          setVisible(false);
//        close();
        new updateDeletePatientRecord().setVisible(true);
                
        }
        
        catch(Exception e)
        {
            System.out.println(e);
           JOptionPane.showMessageDialog(null, "Please enter data in correct formate !"+ e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         String PatientID=patientIdF.getText();
         String AnymajorDiseases=jTextField8.getText();
         try{
             Connection cons =DBConnection.getcon();
             Statement st= cons.createStatement();
             st.executeUpdate("delete from patient where patientID='"+PatientID+"'");
             JOptionPane.showMessageDialog(null, "successfully Deleted");
//             close();
         }
         catch(Exception e)
         {
             JOptionPane.showMessageDialog(null, e);
         }
         
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateDeletePatientRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateDeletePatientRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateDeletePatientRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateDeletePatientRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateDeletePatientRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressF;
    private javax.swing.JTextField AgeF;
    private javax.swing.JTextField BloodGroupF;
    private javax.swing.JTextField ContactNoF;
    private javax.swing.JTextField NameF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField patientIdF;
    // End of variables declaration//GEN-END:variables
}
